/// Flutter icons HealthDialIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  HealthDialIcons
///      fonts:
///       - asset: fonts/HealthDialIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class HealthDialIcons {
  HealthDialIcons._();

  static const _kFontFam = 'HealthDialIcons';
  static const String? _kFontPkg = null;

  static const IconData user = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData blood = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lungs = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData steps = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData temp = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
